export const gift = [
  {
    text: "MOBILES & MORE",
    lists: {
      title: "SmartPhone & Tablets",
      Sidebar: [
        "I KALL",
        "Mi",
        "Realme",
        "Samsung",
        "Vivo",
        "Oppo",
        "Apple",
        "Techno",
        "Micromax",
      ],
      alldata: [
        {
          heading: "Feature Phones",
          child: [
            "Micromax",
            "I KALL",
            "NOKIA",
            "MTR",
            "Heemax",
            "Karbonn",
            "Gfive",
            "Shop All...",
          ],
        },
        {
          heading: "Gaming Consoles",
          child: [
            "Gaming Tiles",
            "Accesories",
            "Under $ 50",
            "Under $ 100",
            "Over $ 100",
            "Shop All...",
          ],
        },
        {
          heading: "Best Sellers",
          child: [
            "Top Rated Accessories",
            "Combos",
            "Cases & Covers",
            "Mobile Holders",
            "Cables",
            "Chargers",
            "Show All...",
          ],
        },
        {
          heading: "Just for Kids",
          child: [
            "Active Gear",
            "Kids Fan Gear",
            "Toys & Games",
            "Gift Cards",
            "Shop All...",
          ],
        },
        {
          heading: "Favorite Brands",
          child: [
            "Brahmin",
            "Estee Lauder",
            "Free People",
            "Michael Kors",
            "Relph Lauren",
            "Shop All...",
          ],
        },
      ],
    },
  },
  {
    text: "Women",
    lists: {
      title: "Women",
      Sidebar: [
        "New Arrivals",
        "Active Shop",
        "Contemporary",
        "Cozy Shop",
        "The Culture Shop",
        "Denim Shop",
        "Designer",
        "Fan Gear",
        "Gifts for Her",
        "Pajamas & Robes",
        "Women`s Clearance",
        "Gift Cards",
      ],
      alldata: [
        {
          heading: "Clothing",
          child: [
            "Lingeries",
            "Coats & Outerwear",
            "Dresses",
            "Pants & Leggings",
            "Sweaters",
            "Shop All...",
          ],
        },
        {
          heading: "Plus Size Clothing",
          child: [
            "Bras, Panties & Lingerie",
            "Dresses",
            "Jeans",
            "Pants",
            "Tops",
            "Shop All...",
          ],
        },
        {
          heading: "Footwear",
          child: [
            "Ballerinas",
            "Casual Shoes",
            "Flats",
            "Heels",
            "Slippers & Flip Flops",
            "Sports Sandals",
            "Sports Shoes",
          ],
        },
        {
          heading: "Women`s Tops",
          child: [
            "Blouses",
            "Button Down Tops",
            "Hoodies & Sweatshirts",
            "Tunices",
            "T-Shirts",
            "Shop All...",
          ],
        },
        {
          heading: "Junior`s Clothing",
          child: [
            "Activewear",
            "Dresses",
            "Jeans",
            "Junior`s Plus",
            "Tops",
            "Shop All...",
          ],
        },
        {
          heading: "Women`s Dresses",
          child: [
            "Casual",
            "Cocktail & Party",
            "Formal",
            "Maxi",
            "Work",
            "Shop All...",
          ],
        },
      ],
    },
  },
  {
    text: "Men",
    lists: {
      title: "Men",
      Sidebar: [
        "New Arrivals",
        "Active Shop",
        "The Culture Shop",
        "Designer",
        "Fan Gear",
        "Formal Wear & Wedding",
        "Gifts for Him",
        "Golf Shop",
        "Men`s Clearance",
        "Gift Cards",
      ],
      alldata: [
        {
          heading: "Clothing",
          child: [
            "Accessories & Combo Sets",
            "Cargos, Shorts & 3/4ths",
            "Ethnic Wear",
            "Fabrics",
            "Inner Wear & Sleep Wear",
            "Jeans",
            "Shirts",
            "Sports Wear",
            "Suits & Blazers",
            "T-Shirts",
            "Trousers",
            "Winter & Seasonal Wear",
          ],
        },
        {
          heading: "Big & Tall Clothing",
          child: [
            "Active & Outdoor",
            "Pants",
            "Polos",
            "Shirts",
            "Suits & Sport Coats",
            "Shop All...",
          ],
        },
        {
          heading: "Young Men's Clothing",
          child: [
            "Active & Outdoor",
            "Graphic Tees",
            "Hoodies & Sweatshirts",
            "Jeans",
            "Shirts",
            "Show All...",
          ],
        },
        {
          heading: "Footwear",
          child: [
            "Casual Shoes",
            "Formal Shoes",
            "Sandals & Floaters",
            "Slippers & Flip Flops",
            "Sports Shoes",
          ],
        },
        {
          heading: "Beauty and Personal Care",
          child: [
            "Sivanna Men's Grooming",
            "Gifts & Gadgets",
            "Hats",
            "Ties & Pocket Squares",
            "Wallets & Money Clips",
            "Shop All...",
          ],
        },
        {
          heading: "Men's Jewelry & Watches",
          child: [
            "Bracelets",
            "Jewelry Sets",
            "Necklaces",
            "Rings",
            "Watches",
            "Shop All...",
          ],
        },
      ],
    },
  },
  {
    text: "Beauty & Health",
    lists: {
      title: "Beauty & Health",
      Sidebar: [
        "New Arrivals",
        "Active Shop",
        "Contemporary",
        "Cozy Shop",
        "The Culture Shop",
        "Denim Shop",
        "Designer",
        "Fan Gear",
        "Gifts for Her",
        "Pajamas & Robes",
        "Women`s Clearance",
        "Gift Cards",
      ],
      alldata: [
        {
          heading: "Clothing",
          child: [
            "Lingeries",
            "Coats & Outerwear",
            "Dresses",
            "Pants & Leggings",
            "Sweaters",
            "Shop All...",
          ],
        },
        {
          heading: "Plus Size Clothing",
          child: [
            "Bras, Panties & Lingerie",
            "Dresses",
            "Jeans",
            "Pants",
            "Tops",
            "Shop All...",
          ],
        },
        {
          heading: "Footwear",
          child: [
            "Ballerinas",
            "Casual Shoes",
            "Flats",
            "Heels",
            "Slippers & Flip Flops",
            "Sports Sandals",
            "Sports Shoes",
          ],
        },
        {
          heading: "Women`s Tops",
          child: [
            "Blouses",
            "Button Down Tops",
            "Hoodies & Sweatshirts",
            "Tunices",
            "T-Shirts",
            "Shop All...",
          ],
        },
        {
          heading: "Junior`s Clothing",
          child: [
            "Activewear",
            "Dresses",
            "Jeans",
            "Junior`s Plus",
            "Tops",
            "Shop All...",
          ],
        },
        {
          heading: "Women`s Dresses",
          child: [
            "Casual",
            "Cocktail & Party",
            "Formal",
            "Maxi",
            "Work",
            "Shop All...",
          ],
        },
      ],
    },
  },
  {
    text: "Wellness",
    lists: {
      title: "Men",
      Sidebar: [
        "New Arrivals",
        "Active Shop",
        "The Culture Shop",
        "Designer",
        "Fan Gear",
        "Formal Wear & Wedding",
        "Gifts for Him",
        "Golf Shop",
        "Men`s Clearance",
        "Gift Cards",
      ],
      alldata: [
        {
          heading: "Clothing",
          child: [
            "Accessories & Combo Sets",
            "Cargos, Shorts & 3/4ths",
            "Ethnic Wear",
            "Fabrics",
            "Inner Wear & Sleep Wear",
            "Jeans",
            "Shirts",
            "Sports Wear",
            "Suits & Blazers",
            "T-Shirts",
            "Trousers",
            "Winter & Seasonal Wear",
          ],
        },
        {
          heading: "Big & Tall Clothing",
          child: [
            "Active & Outdoor",
            "Pants",
            "Polos",
            "Shirts",
            "Suits & Sport Coats",
            "Shop All...",
          ],
        },
        {
          heading: "Young Men's Clothing",
          child: [
            "Active & Outdoor",
            "Graphic Tees",
            "Hoodies & Sweatshirts",
            "Jeans",
            "Shirts",
            "Show All...",
          ],
        },
        {
          heading: "Footwear",
          child: [
            "Casual Shoes",
            "Formal Shoes",
            "Sandals & Floaters",
            "Slippers & Flip Flops",
            "Sports Shoes",
          ],
        },
        {
          heading: "Beauty and Personal Care",
          child: [
            "Sivanna Men's Grooming",
            "Gifts & Gadgets",
            "Hats",
            "Ties & Pocket Squares",
            "Wallets & Money Clips",
            "Shop All...",
          ],
        },
        {
          heading: "Men's Jewelry & Watches",
          child: [
            "Bracelets",
            "Jewelry Sets",
            "Necklaces",
            "Rings",
            "Watches",
            "Shop All...",
          ],
        },
      ],
    },
  },
  {
    text: "Global Shopping",
    lists: {
      title: "Women",
      Sidebar: [
        "New Arrivals",
        "Active Shop",
        "Contemporary",
        "Cozy Shop",
        "The Culture Shop",
        "Denim Shop",
        "Designer",
        "Fan Gear",
        "Gifts for Her",
        "Pajamas & Robes",
        "Women`s Clearance",
        "Gift Cards",
      ],
      alldata: [
        {
          heading: "Clothing",
          child: [
            "Lingeries",
            "Coats & Outerwear",
            "Dresses",
            "Pants & Leggings",
            "Sweaters",
            "Shop All...",
          ],
        },
        {
          heading: "Plus Size Clothing",
          child: [
            "Bras, Panties & Lingerie",
            "Dresses",
            "Jeans",
            "Pants",
            "Tops",
            "Shop All...",
          ],
        },
        {
          heading: "Footwear",
          child: [
            "Ballerinas",
            "Casual Shoes",
            "Flats",
            "Heels",
            "Slippers & Flip Flops",
            "Sports Sandals",
            "Sports Shoes",
          ],
        },
        {
          heading: "Women`s Tops",
          child: [
            "Blouses",
            "Button Down Tops",
            "Hoodies & Sweatshirts",
            "Tunices",
            "T-Shirts",
            "Shop All...",
          ],
        },
        {
          heading: "Junior`s Clothing",
          child: [
            "Activewear",
            "Dresses",
            "Jeans",
            "Junior`s Plus",
            "Tops",
            "Shop All...",
          ],
        },
        {
          heading: "Women`s Dresses",
          child: [
            "Casual",
            "Cocktail & Party",
            "Formal",
            "Maxi",
            "Work",
            "Shop All...",
          ],
        },
      ],
    },
  },
  {
    text: "OFFERS",
    lists: {
      title: "Men",
      Sidebar: [
        "New Arrivals",
        "Active Shop",
        "The Culture Shop",
        "Designer",
        "Fan Gear",
        "Formal Wear & Wedding",
        "Gifts for Him",
        "Golf Shop",
        "Men`s Clearance",
        "Gift Cards",
      ],
      alldata: [
        {
          heading: "Clothing",
          child: [
            "Accessories & Combo Sets",
            "Cargos, Shorts & 3/4ths",
            "Ethnic Wear",
            "Fabrics",
            "Inner Wear & Sleep Wear",
            "Jeans",
            "Shirts",
            "Sports Wear",
            "Suits & Blazers",
            "T-Shirts",
            "Trousers",
            "Winter & Seasonal Wear",
          ],
        },
        {
          heading: "Big & Tall Clothing",
          child: [
            "Active & Outdoor",
            "Pants",
            "Polos",
            "Shirts",
            "Suits & Sport Coats",
            "Shop All...",
          ],
        },
        {
          heading: "Young Men's Clothing",
          child: [
            "Active & Outdoor",
            "Graphic Tees",
            "Hoodies & Sweatshirts",
            "Jeans",
            "Shirts",
            "Show All...",
          ],
        },
        {
          heading: "Footwear",
          child: [
            "Casual Shoes",
            "Formal Shoes",
            "Sandals & Floaters",
            "Slippers & Flip Flops",
            "Sports Shoes",
          ],
        },
        {
          heading: "Beauty and Personal Care",
          child: [
            "Sivanna Men's Grooming",
            "Gifts & Gadgets",
            "Hats",
            "Ties & Pocket Squares",
            "Wallets & Money Clips",
            "Shop All...",
          ],
        },
        {
          heading: "Men's Jewelry & Watches",
          child: [
            "Bracelets",
            "Jewelry Sets",
            "Necklaces",
            "Rings",
            "Watches",
            "Shop All...",
          ],
        },
      ],
    },
  },
];
